spring:
  application:
    name: Finance_Dashboard

jwt:
  secret-key: 9WQbHcbDT3BKDqW4lK4Qhx+pAI4gA2RTB0CH6qL15PLalfsFu46FeyfVpbMqvCSII2rb6zd3Z5yh9G0gTXouAcUFtS3IvtNlNkvH+XAi0sUSUIzXnA5aAjiTE4WcP6QRvUv3dTxcwsp1tTZwRDO6vNaILNXm6+o5Mtlyqvx+9GbFIxTxgOq5kVW6VpwJ93Fj8IbqM7WKlJg62l5HQ8X+CivnXP1fla2JNBO6S9y7t+geuUU1scfArBoPbtyCMFSLD97cmqHQnDvrYZ3RHnT/j6W7elShVLwDrnvL1gTMtPMk+RbQsXLLTtVxYf8cBwBiZOhDDm50Uh9ssoMUHQuNWA==
  access-key:
    expiration:
  refresh-key:
    expiration: